//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AgoraSDKDemoPro.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_AgroaSDKDemoProTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define ID_WND_USERVIEW                 310
#define ID_LIST_USERLIST                311
#define TOOLBAR_NORMAL                  311
#define IDB_TOOLBAR_NORMAL              311
#define ID_TOOLBAR_USERLIST             312
#define IDD_DLGJOIN                     312
#define ID_LIST_LOGLIST                 313
#define ID_TOOLBAR_LOGLIST              314
#define ID_JOIN_TOOLBAR                 315
#define IDB_TBDIS_USERLIST              315
#define ID_LEAVE_TOOLBAR                316
#define IDR_USERLIST                    316
#define ID_MUTEAUDIO_TOOLBAR            317
#define ID_WND1_REMOTEVIDEO             318
#define IDB_BITMAP1                     318
#define IDB_STAT_USERLIST               318
#define ID_WND2_REMOTEVIDEO             319
#define ID_WND3_REMOTEVIDEO             320
#define IDB_SETUP_SHEET                 320
#define ID_WND4_REMOTEVIDEO             321
#define ID_WND_LOCALVIEW                322
#define IDR_TEST_WAVE                   322
#define ID_VIEW_OUTPUTWND               323
#define IDB_BITMAP2                     323
#define IDB_VIDEOWND_BTCTRL             323
#define ID_IPCAMERA_TOOLBAR             324
#define IDW_BIGVIDEO                    325
#define IDD_SETUPPAGE                   325
#define IDW_SMALLVIDEO                  326
#define ID_VIEW_VIDEOLIST               327
#define IDD_DLGMAXVIDEO                 327
#define IDW_LOCALVIDEO                  328
#define ID_WND_REMOTEVIEW               329
#define ID_WND_LOCALVIDEO               330
#define ID_WND_REMOTEVIDEO              331
#define ID_SETUP_TOOLBAR                332
#define IDD_NETWORKTESTPAGE             333
#define IDD_ECHOTESTPAGE                334
#define IDD_DEVICETESTPAGE              335
#define ID_STATUSBAR_USERSTATUS         336
#define ID_STATUSBAR_ROOMINFO           337
#define ID_STATUSBAR_NETINFO            338
#define ID_WND_CHATBOX                  339
#define ID_WND_HISTROYBOX               340
#define ID_BTN_SEND                     341
#define ID_BTN_TESTSEND                 342
#define ID_STATUSBAR_SDKVER             343
#define IDC_EDVKEY_JOIN                 1001
#define IDC_EDID_JOIN                   1002
#define IDC_EDCHANNEL_JOIN              1003
#define IDC_EDPORT_CAMERA               1009
#define IDC_CKTEST_NETWORKTEST          1012
#define IDC_BTNCTR_ECHOTEST             1013
#define IDC_CMBRCDSEL_DEVICETEST        1015
#define IDC_CMBPLOSEL_DEVICETEST        1016
#define IDC_SLDRCDVSET_DEVICETEST       1018
#define IDC_SLDPLOVSET_DEVICETEST       1019
#define IDC_BTNRCDCTRL_DEVICETEST       1020
#define IDC_BTNPLOCTRL_DEVICETEST       1021
#define IDC_CMBWORKMODE_JOIN            1022
#define IDC_CMBDECDMODE_JOIN            1023
#define IDC_CKRECVMODE_JOIN             1024
#define IDC_CMBRSL_SETUP                1025
#define IDC_CMBMAXRESOLUTION_JOIN       1026
#define IDC_STTEXT_                     1027
#define IDC_STTEXT_DEVICETEST           1027
#define ID_BUTTON32771                  32771
#define ID_SWITCHRES_USERLIST           32774
#define ID_MUTESOUND_USERLIST           32775
#define ID_MUTEVIDEO_USERLIST           32776
#define ID_RQSVIDEO_USERLIST            32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        328
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           344
#endif
#endif
